-- CREATE DATABASE SashisuRealmDB

USE SashisuRealmDB
GO

DROP TABLE IF EXISTS Users

-- users table
CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(50) NOT NULL,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Salt NVARCHAR(255) NOT NULL,
  Points INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)

